version: '2'
services:
  memcached:
    image: memcached
    ports:
      - "11211:11211"

  redis:
    image: redis:2.8.23
    ports:
      - "6399:6379"

  db:
    image: postgres:10.2-alpine
    ports:
      - "5440:5432"
